In [1]:
import pandas as pd 
import json
import numpy as np 

from sklearn.model_selection import train_test_split
import matplotlib.pyplot as plt

In [2]:
with open('readings (1).json') as f:
    data = json.load(f)

df = pd.json_normalize(data)

In [3]:
df

,timestamp,devices,aggregate_energy_wh
0,1.752172e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",2.7806
1,1.752172e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",5.5612
2,1.752172e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",8.3418
3,1.752172e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",11.1224
4,1.752172e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",13.9030
...,...,...,...
9995,1.752182e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",27794.8776
9996,1.752182e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",27797.6582
9997,1.752182e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",27800.4388
9998,1.752182e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",27803.2194
9999,1.752182e+09,"[{'device': 'washing_machine', 'count': 1, 'vo...",27806.0000

In [4]:
data

[{'timestamp': 1752172067.6229844,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 213.33,
    'current': 2.34,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 229.14,
    'current': 0.65,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 221.61,
    'current': 9.02,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 225.74,
    'current': 6.64,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 212.96,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 225.16,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 211.44,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 222.15,
    'current': 0.45,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 218.52,
    'current': 0.27,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 2.7806},
 {'timestamp': 1752172068.6348004,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 216.48,
    'current': 2.31,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 214.53,
    'current': 0.7,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 215.25,
    'current': 9.29,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 212.27,
    'current': 7.07,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 213.45,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 226.42,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 213.54,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 212.35,
    'current': 0.47,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 219.18,
    'current': 0.27,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 5.5612},
 {'timestamp': 1752172069.6393797,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 226.61,
    'current': 2.21,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 227.58,
    'current': 0.66,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 227.11,
    'current': 8.81,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 220.38,
    'current': 6.81,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 224.75,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 225.12,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 221.09,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 225.82,
    'current': 0.44,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 211.44,
    'current': 0.28,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 8.3418},
 {'timestamp': 1752172070.6482847,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 227.08,
    'current': 2.2,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 216.69,
    'current': 0.69,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 216.98,
    'current': 9.22,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 229.26,
    'current': 6.54,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 215.19,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 224.5,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 226.03,
    'current': 0.04,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 225.01,
    'current': 0.44,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 216.55,
    'current': 0.28,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 11.1224},
 {'timestamp': 1752172071.6598334,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 215.29,
    'current': 2.32,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 216.55,
    'current': 0.69,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 222.64,
    'current': 8.98,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 224.09,
    'current': 6.69,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 219.97,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 218.23,
    'current': 0.23,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 215.24,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 224.82,
    'current': 0.44,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 215.59,
    'current': 0.28,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 13.903},
 {'timestamp': 1752172072.6706278,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 226.55,
    'current': 2.21,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 214.23,
    'current': 0.7,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 224.82,
    'current': 8.9,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 222.34,
    'current': 6.75,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 215.67,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 216.43,
    'current': 0.23,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 227.08,
    'current': 0.04,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 224.36,
    'current': 0.45,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 220.51,
    'current': 0.27,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 16.6836},
 {'timestamp': 1752172073.6807675,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 223.18,
    'current': 2.24,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 218.23,
    'current': 0.69,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 219.19,
    'current': 9.12,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 221.26,
    'current': 6.78,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 226.31,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 228.36,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 217.41,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 224.74,
    'current': 0.44,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 226.56,
    'current': 0.26,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 19.4642},
 {'timestamp': 1752172074.6921098,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 210.58,
    'current': 2.37,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 219.07,
    'current': 0.68,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 218.86,
    'current': 9.14,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 220.85,
    'current': 6.79,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 226.46,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 215.14,
    'current': 0.23,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 222.33,
    'current': 0.04,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 214.77,
    'current': 0.47,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 212.05,
    'current': 0.28,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 22.2448},
 {'timestamp': 1752172075.7001956,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 217.55,
    'current': 2.3,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 211.98,
    'current': 0.71,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 223.26,
    'current': 8.96,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 213.91,
    'current': 7.01,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 216.1,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 228.72,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 226.5,
    'current': 0.04,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 215.81,
    'current': 0.46,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 227.66,
    'current': 0.26,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 25.0254},
 {'timestamp': 1752172076.7102382,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 227.27,
    'current': 2.2,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 214.77,
    'current': 0.7,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 228.97,
    'current': 8.73,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 210.25,
    'current': 7.13,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 214.81,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 219.25,
    'current': 0.23,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 210.23,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 225.58,
    'current': 0.44,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 218.03,
    'current': 0.28,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 27.806},
 {'timestamp': 1752172077.724206,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 222.94,
    'current': 2.24,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 217.21,
    'current': 0.69,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 221.01,
    'current': 9.05,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 215.04,
    'current': 6.98,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 215.14,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 222.92,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 226.39,
    'current': 0.04,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 211.37,
    'current': 0.47,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 213.73,
    'current': 0.28,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 30.5866},
 {'timestamp': 1752172078.7391546,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 225.99,
    'current': 2.21,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 223.23,
    'current': 0.67,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 228.73,
    'current': 8.74,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 222.37,
    'current': 6.75,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 216.1,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 228.85,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 227.41,
    'current': 0.04,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 216.37,
    'current': 0.46,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 219.89,
    'current': 0.27,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 33.3672},
 {'timestamp': 1752172079.7429414,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 216.31,
    'current': 2.31,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 215.55,
    'current': 0.7,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 215.43,
    'current': 9.28,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 224.37,
    'current': 6.69,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 219.22,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 224.64,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 214.64,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 220.54,
    'current': 0.45,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 216.84,
    'current': 0.28,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 36.1478},
 {'timestamp': 1752172080.7547169,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 219.35,
    'current': 2.28,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 215.53,
    'current': 0.7,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 218.64,
    'current': 9.15,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 227.63,
    'current': 6.59,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 220.23,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 229.65,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 218.23,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 224.41,
    'current': 0.45,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 228.8,
    'current': 0.26,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 38.9284},
 {'timestamp': 1752172081.760651,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 223.47,
    'current': 2.24,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 211.42,
    'current': 0.71,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 226.59,
    'current': 8.83,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 213.49,
    'current': 7.03,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 227.11,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 225.61,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 221.45,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 228.72,
    'current': 0.44,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 227.44,
    'current': 0.26,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 41.709},
 {'timestamp': 1752172082.765391,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 221.34,
    'current': 2.26,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 215.65,
    'current': 0.7,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 214.02,
    'current': 9.34,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 225.92,
    'current': 6.64,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 224.08,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 224.86,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 211.24,
    'current': 0.05,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 216.25,
    'current': 0.46,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 227.38,
    'current': 0.26,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 44.4896},
 {'timestamp': 1752172083.772725,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 222.86,
    'current': 2.24,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 226.75,
    'current': 0.66,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 226.33,
    'current': 8.84,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 212.8,
    'current': 7.05,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 228.49,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 215.11,
    'current': 0.23,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 223.93,
    'current': 0.04,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 224.64,
    'current': 0.45,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 215.15,
    'current': 0.28,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 47.2702},
 {'timestamp': 1752172084.7827017,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 218.82,
    'current': 2.28,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 229.55,
    'current': 0.65,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 226.25,
    'current': 8.84,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,
    'voltage': 212.84,
    'current': 7.05,
    'energy_wh': 0.8333},
   {'device': 'tubelight',
    'count': 4,
    'voltage': 223.28,
    'current': 0.09,
    'energy_wh': 0.0222},
   {'device': 'fan',
    'count': 3,
    'voltage': 228.87,
    'current': 0.22,
    'energy_wh': 0.0417},
   {'device': 'led_light',
    'count': 5,
    'voltage': 229.84,
    'current': 0.04,
    'energy_wh': 0.0139},
   {'device': 'tv',
    'count': 1,
    'voltage': 210.02,
    'current': 0.48,
    'energy_wh': 0.0278},
   {'device': 'laptop',
    'count': 2,
    'voltage': 225.71,
    'current': 0.27,
    'energy_wh': 0.0333}],
  'aggregate_energy_wh': 50.0508},
 {'timestamp': 1752172085.790759,
  'devices': [{'device': 'washing_machine',
    'count': 1,
    'voltage': 212.31,
    'current': 2.36,
    'energy_wh': 0.1389},
   {'device': 'refrigerator',
    'count': 1,
    'voltage': 227.09,
    'current': 0.66,
    'energy_wh': 0.0417},
   {'device': 'water_heater',
    'count': 1,
    'voltage': 212.81,
    'current': 9.4,
    'energy_wh': 0.5556},
   {'device': 'ac',
    'count': 2,

In [5]:
data[0]

{'timestamp': 1752172067.6229844,
 'devices': [{'device': 'washing_machine',
   'count': 1,
   'voltage': 213.33,
   'current': 2.34,
   'energy_wh': 0.1389},
  {'device': 'refrigerator',
   'count': 1,
   'voltage': 229.14,
   'current': 0.65,
   'energy_wh': 0.0417},
  {'device': 'water_heater',
   'count': 1,
   'voltage': 221.61,
   'current': 9.02,
   'energy_wh': 0.5556},
  {'device': 'ac',
   'count': 2,
   'voltage': 225.74,
   'current': 6.64,
   'energy_wh': 0.8333},
  {'device': 'tubelight',
   'count': 4,
   'voltage': 212.96,
   'current': 0.09,
   'energy_wh': 0.0222},
  {'device': 'fan',
   'count': 3,
   'voltage': 225.16,
   'current': 0.22,
   'energy_wh': 0.0417},
  {'device': 'led_light',
   'count': 5,
   'voltage': 211.44,
   'current': 0.05,
   'energy_wh': 0.0139},
  {'device': 'tv',
   'count': 1,
   'voltage': 222.15,
   'current': 0.45,
   'energy_wh': 0.0278},
  {'device': 'laptop',
   'count': 2,
   'voltage': 218.52,
   'current': 0.27,
   'energy_wh': 0.0333}],
 'aggregate_energy_wh': 2.7806}

In [6]:
data[0].items()

dict_items([('timestamp', 1752172067.6229844), ('devices', [{'device': 'washing_machine', 'count': 1, 'voltage': 213.33, 'current': 2.34, 'energy_wh': 0.1389}, {'device': 'refrigerator', 'count': 1, 'voltage': 229.14, 'current': 0.65, 'energy_wh': 0.0417}, {'device': 'water_heater', 'count': 1, 'voltage': 221.61, 'current': 9.02, 'energy_wh': 0.5556}, {'device': 'ac', 'count': 2, 'voltage': 225.74, 'current': 6.64, 'energy_wh': 0.8333}, {'device': 'tubelight', 'count': 4, 'voltage': 212.96, 'current': 0.09, 'energy_wh': 0.0222}, {'device': 'fan', 'count': 3, 'voltage': 225.16, 'current': 0.22, 'energy_wh': 0.0417}, {'device': 'led_light', 'count': 5, 'voltage': 211.44, 'current': 0.05, 'energy_wh': 0.0139}, {'device': 'tv', 'count': 1, 'voltage': 222.15, 'current': 0.45, 'energy_wh': 0.0278}, {'device': 'laptop', 'count': 2, 'voltage': 218.52, 'current': 0.27, 'energy_wh': 0.0333}]), ('aggregate_energy_wh', 2.7806)])

In [7]:
print(data[0].items())

dict_items([('timestamp', 1752172067.6229844), ('devices', [{'device': 'washing_machine', 'count': 1, 'voltage': 213.33, 'current': 2.34, 'energy_wh': 0.1389}, {'device': 'refrigerator', 'count': 1, 'voltage': 229.14, 'current': 0.65, 'energy_wh': 0.0417}, {'device': 'water_heater', 'count': 1, 'voltage': 221.61, 'current': 9.02, 'energy_wh': 0.5556}, {'device': 'ac', 'count': 2, 'voltage': 225.74, 'current': 6.64, 'energy_wh': 0.8333}, {'device': 'tubelight', 'count': 4, 'voltage': 212.96, 'current': 0.09, 'energy_wh': 0.0222}, {'device': 'fan', 'count': 3, 'voltage': 225.16, 'current': 0.22, 'energy_wh': 0.0417}, {'device': 'led_light', 'count': 5, 'voltage': 211.44, 'current': 0.05, 'energy_wh': 0.0139}, {'device': 'tv', 'count': 1, 'voltage': 222.15, 'current': 0.45, 'energy_wh': 0.0278}, {'device': 'laptop', 'count': 2, 'voltage': 218.52, 'current': 0.27, 'energy_wh': 0.0333}]), ('aggregate_energy_wh', 2.7806)])

In [8]:
df['devices']

0       [{'device': 'washing_machine', 'count': 1, 'vo...
1       [{'device': 'washing_machine', 'count': 1, 'vo...
2       [{'device': 'washing_machine', 'count': 1, 'vo...
3       [{'device': 'washing_machine', 'count': 1, 'vo...
4       [{'device': 'washing_machine', 'count': 1, 'vo...
                              ...
9995    [{'device': 'washing_machine', 'count': 1, 'vo...
9996    [{'device': 'washing_machine', 'count': 1, 'vo...
9997    [{'device': 'washing_machine', 'count': 1, 'vo...
9998    [{'device': 'washing_machine', 'count': 1, 'vo...
9999    [{'device': 'washing_machine', 'count': 1, 'vo...
Name: devices, Length: 10000, dtype: object

In [9]:
rows = []
for entry in data:
    timestamp = entry["timestamp"]
    device_data = entry["devices"]
    aggregate_energy_wh = entry["aggregate_energy_wh"]
    for device in entry['devices']:
        device_row =device.copy()
        device_row['timestamp']=timestamp
        device_row['aggregate_energy_wh']=aggregate_energy_wh
        rows.append(device_row)

df = pd.DataFrame(rows)

In [10]:
df

,device,count,voltage,current,energy_wh,timestamp,aggregate_energy_wh
0,washing_machine,1,213.33,2.34,0.1389,1.752172e+09,2.7806
1,refrigerator,1,229.14,0.65,0.0417,1.752172e+09,2.7806
2,water_heater,1,221.61,9.02,0.5556,1.752172e+09,2.7806
3,ac,2,225.74,6.64,0.8333,1.752172e+09,2.7806
4,tubelight,4,212.96,0.09,0.0222,1.752172e+09,2.7806
...,...,...,...,...,...,...,...
89995,tubelight,4,223.63,0.09,0.0222,1.752182e+09,27806.0000
89996,fan,3,214.61,0.23,0.0417,1.752182e+09,27806.0000
89997,led_light,5,213.48,0.05,0.0139,1.752182e+09,27806.0000
89998,tv,1,218.40,0.46,0.0278,1.752182e+09,27806.0000
89999,laptop,2,215.47,0.28,0.0333,1.752182e+09,27806.0000

In [11]:
df

,device,count,voltage,current,energy_wh,timestamp,aggregate_energy_wh
0,washing_machine,1,213.33,2.34,0.1389,1.752172e+09,2.7806
1,refrigerator,1,229.14,0.65,0.0417,1.752172e+09,2.7806
2,water_heater,1,221.61,9.02,0.5556,1.752172e+09,2.7806
3,ac,2,225.74,6.64,0.8333,1.752172e+09,2.7806
4,tubelight,4,212.96,0.09,0.0222,1.752172e+09,2.7806
...,...,...,...,...,...,...,...
89995,tubelight,4,223.63,0.09,0.0222,1.752182e+09,27806.0000
89996,fan,3,214.61,0.23,0.0417,1.752182e+09,27806.0000
89997,led_light,5,213.48,0.05,0.0139,1.752182e+09,27806.0000
89998,tv,1,218.40,0.46,0.0278,1.752182e+09,27806.0000
89999,laptop,2,215.47,0.28,0.0333,1.752182e+09,27806.0000

In [12]:
df.columns.to_list()

['device',
 'count',
 'voltage',
 'current',
 'energy_wh',
 'timestamp',
 'aggregate_energy_wh']

In [13]:
df['device'].value_counts()

device
washing_machine    10000
refrigerator       10000
water_heater       10000
ac                 10000
tubelight          10000
fan                10000
led_light          10000
tv                 10000
laptop             10000
Name: count, dtype: int64

In [14]:
df.isnull().sum()

device                 0
count                  0
voltage                0
current                0
energy_wh              0
timestamp              0
aggregate_energy_wh    0
dtype: int64

In [15]:
df.describe()

,count,voltage,current,energy_wh,timestamp,aggregate_energy_wh
count,90000.000000,90000.000000,90000.000000,90000.000000,9.000000e+04,90000.000000
mean,2.222222,219.986597,2.218586,0.189822,1.752177e+09,13904.390300
std,1.396653,5.771317,3.180855,0.279709,2.918003e+03,8026.945347
min,1.000000,210.000000,0.040000,0.013900,1.752172e+09,2.780600
25%,1.000000,214.987500,0.220000,0.027800,1.752175e+09,6953.585450
50%,2.000000,219.980000,0.450000,0.041700,1.752177e+09,13904.390300
75%,3.000000,224.990000,2.330000,0.138900,1.752180e+09,20855.195150
max,5.000000,230.000000,9.520000,0.833300,1.752182e+09,27806.000000

In [16]:
df['timestamp'].iloc

In [17]:
df['timestamp'].iloc[0]

np.float64(1752172067.6229844)

In [18]:
df['timestamp'] = pd.to_datetime(df['timestamp'],unit='s')

In [19]:
df

,device,count,voltage,current,energy_wh,timestamp,aggregate_energy_wh
0,washing_machine,1,213.33,2.34,0.1389,2025-07-10 18:27:47.622984409,2.7806
1,refrigerator,1,229.14,0.65,0.0417,2025-07-10 18:27:47.622984409,2.7806
2,water_heater,1,221.61,9.02,0.5556,2025-07-10 18:27:47.622984409,2.7806
3,ac,2,225.74,6.64,0.8333,2025-07-10 18:27:47.622984409,2.7806
4,tubelight,4,212.96,0.09,0.0222,2025-07-10 18:27:47.622984409,2.7806
...,...,...,...,...,...,...,...
89995,tubelight,4,223.63,0.09,0.0222,2025-07-10 21:16:15.741518497,27806.0000
89996,fan,3,214.61,0.23,0.0417,2025-07-10 21:16:15.741518497,27806.0000
89997,led_light,5,213.48,0.05,0.0139,2025-07-10 21:16:15.741518497,27806.0000
89998,tv,1,218.40,0.46,0.0278,2025-07-10 21:16:15.741518497,27806.0000
89999,laptop,2,215.47,0.28,0.0333,2025-07-10 21:16:15.741518497,27806.0000

In [20]:
df['timestamp']

0       2025-07-10 18:27:47.622984409
1       2025-07-10 18:27:47.622984409
2       2025-07-10 18:27:47.622984409
3       2025-07-10 18:27:47.622984409
4       2025-07-10 18:27:47.622984409
                     ...
89995   2025-07-10 21:16:15.741518497
89996   2025-07-10 21:16:15.741518497
89997   2025-07-10 21:16:15.741518497
89998   2025-07-10 21:16:15.741518497
89999   2025-07-10 21:16:15.741518497
Name: timestamp, Length: 90000, dtype: datetime64[ns]

In [21]:
df['timestamp'].dt.year

0        2025
1        2025
2        2025
3        2025
4        2025
         ...
89995    2025
89996    2025
89997    2025
89998    2025
89999    2025
Name: timestamp, Length: 90000, dtype: int32

In [22]:
df['year']=df['timestamp'].dt.year
df['month']=df['timestamp'].dt.month
df['day']=df['timestamp'].dt.day
df['hour']=df['timestamp'].dt.hour
df['mint']=df['timestamp'].dt.minute
df['sec']=df['timestamp'].dt.second

In [23]:
df

,device,count,voltage,current,energy_wh,timestamp,aggregate_energy_wh,year,month,day,hour,mint,sec
0,washing_machine,1,213.33,2.34,0.1389,2025-07-10 18:27:47.622984409,2.7806,2025,7,10,18,27,47
1,refrigerator,1,229.14,0.65,0.0417,2025-07-10 18:27:47.622984409,2.7806,2025,7,10,18,27,47
2,water_heater,1,221.61,9.02,0.5556,2025-07-10 18:27:47.622984409,2.7806,2025,7,10,18,27,47
3,ac,2,225.74,6.64,0.8333,2025-07-10 18:27:47.622984409,2.7806,2025,7,10,18,27,47
4,tubelight,4,212.96,0.09,0.0222,2025-07-10 18:27:47.622984409,2.7806,2025,7,10,18,27,47
...,...,...,...,...,...,...,...,...,...,...,...,...,...
89995,tubelight,4,223.63,0.09,0.0222,2025-07-10 21:16:15.741518497,27806.0000,2025,7,10,21,16,15
89996,fan,3,214.61,0.23,0.0417,2025-07-10 21:16:15.741518497,27806.0000,2025,7,10,21,16,15
89997,led_light,5,213.48,0.05,0.0139,2025-07-10 21:16:15.741518497,27806.0000,2025,7,10,21,16,15
89998,tv,1,218.40,0.46,0.0278,2025-07-10 21:16:15.741518497,27806.0000,2025,7,10,21,16,15
89999,laptop,2,215.47,0.28,0.0333,2025-07-10 21:16:15.741518497,27806.0000,2025,7,10,21,16,15

In [24]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
count,90000.0,2.222222,1.0,1.0,2.0,3.0,5.0,1.396653
voltage,90000.0,219.986597,210.0,214.9875,219.98,224.99,230.0,5.771317
current,90000.0,2.218586,0.04,0.22,0.45,2.33,9.52,3.180855
energy_wh,90000.0,0.189822,0.0139,0.0278,0.0417,0.1389,0.8333,0.279709
timestamp,90000,2025-07-10 19:52:02.696269824,2025-07-10 18:27:47.622984409,2025-07-10 19:09:56.999004416,2025-07-10 19:52:03.252500480,2025-07-10 20:34:09.343598336,2025-07-10 21:16:15.741518497,NaN
aggregate_energy_wh,90000.0,13904.3903,2.7806,6953.58545,13904.3903,20855.19515,27806.0,8026.945347
year,90000.0,2025.0,2025.0,2025.0,2025.0,2025.0,2025.0,0.0
month,90000.0,7.0,7.0,7.0,7.0,7.0,7.0,0.0
day,90000.0,10.0,10.0,10.0,10.0,10.0,10.0,0.0
hour,90000.0,19.3584,18.0,19.0,19.0,20.0,21.0,0.897306
mint,90000.0,30.0411,0.0,14.0,31.0,45.0,59.0,17.748744
sec,90000.0,29.49,0.0,14.0,29.0,45.0,59.0,17.336102

In [25]:
df.head(1)

,device,count,voltage,current,energy_wh,timestamp,aggregate_energy_wh,year,month,day,hour,mint,sec
0,washing_machine,1,213.33,2.34,0.1389,2025-07-10 18:27:47.622984409,2.7806,2025,7,10,18,27,47

In [26]:
# Prepare input (X) and output (y)
X = []
y = []
sec = 1
for reading in data:
    devices = reading["devices"]
    sample = []
    total_energy = 0
    for device in devices:
        energy_wh = device["energy_wh"]
        count = device["count"]
        
        # Append [energy, count] as input
        sample.append([energy_wh, count, sec])

In [27]:
sample

[[0.1389, 1, 1],
 [0.0417, 1, 1],
 [0.5556, 1, 1],
 [0.8333, 2, 1],
 [0.0222, 4, 1],
 [0.0417, 3, 1],
 [0.0139, 5, 1],
 [0.0278, 1, 1],
 [0.0333, 2, 1]]

In [28]:
# Compute correct total
total_energy += energy_wh * count

X.append(sample)
y.append(total_energy*sec)
sec += 1
# Convert to numpy arrays
X = np.array(X)  # shape: (n_samples, 9, 2)
y = np.array(y)  # shape: (n_samples,)

In [29]:
total_energy

0.0666

In [30]:
X

array([[[0.1389, 1.    , 1.    ],
        [0.0417, 1.    , 1.    ],
        [0.5556, 1.    , 1.    ],
        [0.8333, 2.    , 1.    ],
        [0.0222, 4.    , 1.    ],
        [0.0417, 3.    , 1.    ],
        [0.0139, 5.    , 1.    ],
        [0.0278, 1.    , 1.    ],
        [0.0333, 2.    , 1.    ]]])

In [31]:
y

array([0.0666])

In [32]:
X.shape

(1, 9, 3)

In [33]:
y.shape

(1,)